# Generated by Django 5.1.2 on 2024-10-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('meeting', 'Meeting'), ('workshop', 'Workshop')], max_length=50)),
                ('preferences', models.TextField()),
                ('requested_date', models.DateField()),
                ('budget', models.IntegerField(null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
