# Generated by Django 5.1.2 on 2024-10-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_remove_clientrequest_admin_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('photography', 'Photography'), ('music', 'Music'), ('graphic_design', 'Graphic Design'), ('decoration', 'Decoration'), ('network_support', 'Network Support')], max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('subteam', models.CharField(choices=[('photography', 'Photography'), ('music', 'Music'), ('graphic_design', 'Graphic Design'), ('decoration', 'Decoration'), ('network_support', 'Network Support')], max_length=50)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Needs Budget', 'Needs Budget')], default='Assigned', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('extra_budget_needed', models.BooleanField(default=False)),
                ('sent_to_production', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
