# Generated by Django 5.1.2 on 2024-10-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_subteam_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_recruits', models.IntegerField(null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('sent_to_hr', models.BooleanField(default=False)),
                ('sent_to_production', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
            ],
        ),
    ]
