# Generated by Django 5.1.2 on 2024-10-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_recruitment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetIncreaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
