# Generated by Django 5.1.2 on 2024-10-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_budgetincreaserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetincreaserequest',
            name='sent_to_production',
            field=models.BooleanField(default=False),
        ),
    ]
