# Generated by Django 5.1.2 on 2024-10-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_budgetincreaserequest_sent_to_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='sent_to_admin',
            field=models.BooleanField(default=False),
        ),
    ]
